<?php  //[STAMP] 3591fe659197a28dfb248321f69f13a5
namespace CubicMushroom\Payments\Stripe\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use CubicMushroom\Payments\Stripe\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
